### ISSUE TITLE
Issue building with Metro / Expo

### ISSUE THREAD

**Issue by bchaney** [tunoltd/emoji-mart-native#67]
I'm trying to build an app that is running through Expo but am getting a weird error. I'm currently using `0.4.6-beta` Whenever I try to open the app I receive an error message that `getSanitizedData` is undefined when using it in `nimble-emoji-index` If I change the inclusion of `getSanitizedData` to be `../../utils` instead of just `..` everything works fine.

Has anyone else experienced this?

**Comment by pederjohnsen** [comment]
Hey @bchaney sorry for the late response!

We've not tested `emoji-mart-native` with Expo apps, did you find a solution? :)
I'm hoping to spend some time over the next couple months going through all issues etc and getting the lib to v1.0. It would be great to get this issue solved as well for that :)

**Comment by rg4real** [comment]
Using `emoji-mart-native` with latest `expo`.

Everything works fine.

**Comment by pederjohnsen** [comment]
Will close for now, if you can still replicate @bchaney let me know and I'll re-open

**Comment by schneidmaster** [comment]
For what it's worth, I'm now able to replicate on the latest version of Expo (though for some reason it does not replicate in a Snack, not sure if those are built differently or something). Our fix was just to fork and change this import from `..` to `../` (https://github.com/aha-app/emoji-mart-native/pull/1). I don't have a good explanation for the issue, but happy to submit a PR if you want since this should make no logical difference anywhere else.

**Comment by pederjohnsen** [comment]
@schneidmaster please do :)
